/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 26 Sep, 2011, 3:32:22 PM
 */
package netbeanjavaclinic;
import java.awt.event.*;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener,FocusListener,ListSelectionListener{
    PatientVO cvo;
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        jButton2.setVisible(false);
         jButton1.addActionListener(this);
         jList1.addListSelectionListener(this);
          jList2.addListSelectionListener(this);
          jList3.addListSelectionListener(this);
           jList4.addListSelectionListener(this);
           jList5.addListSelectionListener(this);
         jTextField1.setVisible(false);
         jTextField2.addFocusListener(this);
          jTextField3.addFocusListener(this);
          jList1.setVisible(false);
         jList2.setVisible(false);
        // jLabel26.setText(cvo.name);
          this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
         dg=new Dignosis();
         
       // cvo=new CustValuObj();
    }
    
    public void setCvo(PatientVO cvo)
    {
        this.cvo=cvo;
        
    }
    
    public void actionPerformed(ActionEvent ae)
     {
         //cvo.durill=duration.getSelectedItem(); 
         
          if(jTextField2.getText().equals(""))
        this.cvo.pastfh="no family history";
          else
         this.cvo.pastfh=jTextField2.getText();
           if(jTextField3.getText().equals(""))
        this.cvo.medh="no medical history";
          else
          this.cvo.medh=jTextField3.getText(); 
        this.cvo.durill=(String)jComboBox1.getSelectedItem(); 
        this.cvo.sleep=(String)jComboBox4.getSelectedItem(); 
         this.cvo.aptit=(String)jComboBox5.getSelectedItem(); 
        this.cvo.palpi=(String)jComboBox6.getSelectedItem(); 
        
                
        this.cvo.trem=(String)jComboBox7.getSelectedItem(); 
         this.cvo.hallu=(String)jComboBox8.getText(); 
         this.cvo.delu=(String)jComboBox9.getText(); 
         this.cvo.insight=(String)jComboBox10.getSelectedItem(); 
          this.cvo.judg=(String)jComboBox11.getSelectedItem(); 
        this.cvo.dreaming=(String)jComboBox18.getSelectedItem(); 
        
         
         
         
        this.cvo.orien=(String)jComboBox13.getSelectedItem(); 
        this.cvo.recentm=(String)jComboBox14.getSelectedItem(); 
        this.cvo.remotm=(String)jComboBox15.getSelectedItem(); 
         this.cvo.cstate=(String)jComboBox16.getSelectedItem(); 
         this.cvo.mood=(String)jComboBox17.getSelectedItem(); 
       //  this.cvo.others=(String)jComboBox18.getSelectedItem();  
          this.cvo.others=(String)jTextArea1.getText();
         this.cvo.pers1=(String)jComboBox19.getSelectedItem();
         this.cvo.pers2=(String)jComboBox20.getSelectedItem();
         this.cvo.pers3=(String)jComboBox21.getSelectedItem();
         this.cvo.pers4=(String)jComboBox22.getSelectedItem();
         this.cvo.pers5=(String)jComboBox23.getSelectedItem();
         this.cvo.pers6=(String)jComboBox24.getSelectedItem();
         
         dg.cvo=this.cvo;
         
         System.out.println(cvo);
         this.setVisible(false);
         dg.setVisible(true); 
         
         
        //cvo.setAdres(jTextField1.getText());
       // System.out.println("cvo"+cvo);    
        
        
      //   int x=  CustDao.insertCust(cvo);
     //  System.out.println("x"+x);
        
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextField3 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jComboBox8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jComboBox9 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox();
        jComboBox17 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox13 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jComboBox24 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();

        jFrame1.setName("jFrame1"); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame2.setName("jFrame2"); // NOI18N

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(netbeanjavaclinic.NetbeanJavaClinicApp.class).getContext().getResourceMap(NewJFrame.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setForeground(resourceMap.getColor("Form.foreground")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(898, 1332, 52, 20);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(434, 479, 163, 23);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(271, 1331, 81, 23);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel1.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jComboBox1.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1Week", "2Week", "3Week", "1Month", "2Month", "3Month", "4Month", "5Month", "6Month", "8Month", "1Year", "1-2Y", "2-4Y", "4-5Yr", "5-15Y", ">15Y" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList2.setFont(resourceMap.getFont("jList2.font")); // NOI18N
        jList2.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Asthama", "Arthritis", "Cardiac Disease", "DM", "Hemiplegia", "HT", "Infective Disease", "Paraplegia", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setName("jList2"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 160, 90));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jList3.setFont(resourceMap.getFont("jList3.font")); // NOI18N
        jList3.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Abuses", "Bizzare", "Calling Names", "Derogatory", "Olfactory", "Ordering ", "Persicutary", "TactileAnts", "Tactile-Feelings", "Third Person", "Visual-Animals", "Visual-HumanBeings", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setName("jList3"); // NOI18N
        jScrollPane3.setViewportView(jList3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, 90));

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jList4.setFont(resourceMap.getFont("jList4.font")); // NOI18N
        jList4.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Black Magic", "Insect Infestation", "Infidelity", "Nihilism", "Persicutary", "Refernciality", "Sex Change", "Somatic", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList4.setName("jList4"); // NOI18N
        jScrollPane4.setViewportView(jList4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 120, 90));

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jTextField2.setColumns(20);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2.setLineWrap(true);
        jTextField2.setRows(5);
        jTextField2.setName("jTextField2"); // NOI18N
        jScrollPane7.setViewportView(jTextField2);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 90));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setFont(resourceMap.getFont("jList1.font")); // NOI18N
        jList1.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Same PSY Illnes", "OtherPSY Illness", "Medical Illness", "Suicide" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 90));

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        jTextField3.setColumns(20);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jTextField3.setLineWrap(true);
        jTextField3.setRows(5);
        jTextField3.setName("jTextField3"); // NOI18N
        jScrollPane8.setViewportView(jTextField3);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 160, 90));

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        jComboBox8.setColumns(20);
        jComboBox8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox8.setLineWrap(true);
        jComboBox8.setRows(5);
        jComboBox8.setName("jComboBox8"); // NOI18N
        jScrollPane9.setViewportView(jComboBox8);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 130, 90));

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        jComboBox9.setColumns(20);
        jComboBox9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox9.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox9.setLineWrap(true);
        jComboBox9.setRows(5);
        jComboBox9.setName("jComboBox9"); // NOI18N
        jScrollPane10.setViewportView(jComboBox9);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 120, 90));

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -20, 190, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 30, 690, 220);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 39, -1));

        jComboBox4.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disturbed", "EMAwake", "Excessive", "LateOnset", "No Sleep", "No Sleep Disturbance", "LateOnset+Early Awake", "LateOnset+Early Awake+DisturbedSleep", " ", " " }));
        jComboBox4.setName("sleep"); // NOI18N
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jComboBox10.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Present", "Absent" }));
        jComboBox10.setName("insight"); // NOI18N
        jPanel2.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jComboBox5.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Less", "More" }));
        jComboBox5.setName("jComboBox5"); // NOI18N
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, -1));

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jComboBox11.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Present", "Impaired" }));
        jComboBox11.setName("jComboBox11"); // NOI18N
        jPanel2.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jComboBox6.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Present", "Absent" }));
        jComboBox6.setName("jComboBox6"); // NOI18N
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jComboBox12.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        jComboBox12.setName("jComboBox12"); // NOI18N
        jPanel2.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 177, 0, -1));

        jComboBox18.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox18.setForeground(resourceMap.getColor("jComboBox18.foreground")); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dead bodies", "height", "others", "snakes", "water", " " }));
        jComboBox18.setName("jComboBox18"); // NOI18N
        jPanel2.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, 20));

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jComboBox16.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        jComboBox16.setName("CState"); // NOI18N
        jPanel2.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        jComboBox17.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nil", "Dysphoric", "Irritable", "Elated" }));
        jComboBox17.setName("jComboBox17"); // NOI18N
        jPanel2.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jPanel3.setName("jPanel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(760, 10, 360, 270);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox13.setEditable(true);
        jComboBox13.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox13.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oriented", "Not Oriented to Place", "Not Oriented to Person", "Not Oriented to Time", "Not Oriented to Place,Person", "Not Oriented to Place,Person,Time", "Not Oriented to Place,Time", "Not Oriented toTime,Person" }));
        jComboBox13.setName("Orient"); // NOI18N
        jPanel4.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 70, 40));

        jComboBox7.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Present", "Absent" }));
        jComboBox7.setName("Tremers"); // NOI18N
        jPanel4.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 74, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 20));

        jComboBox14.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intact", "Impaired" }));
        jComboBox14.setName("RecentM"); // NOI18N
        jPanel4.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 88, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));

        jComboBox15.setFont(resourceMap.getFont("RecentM.font")); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intact", "Impaired" }));
        jComboBox15.setName("RemoteM"); // NOI18N
        jPanel4.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 76, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(212, 270, 480, 101);

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 250, 90, 10);

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jList5.setFont(resourceMap.getFont("jList5.font")); // NOI18N
        jList5.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "ABUSIVE", "AGGRESSIVE  BEHA", "body ache/", "BURNING IN HEAD", "chocking sensation/", "DROPS  ON  PANTS ", "excess socialization/", "F B IN  THROAT", "fear of  disease", "fear of death", "FEAR OF DIS ", "FEAR OF DIS    MALI", "FEARFULLNESS", "FORGETFUL", "ghabarahat", "giddiness", "GRANDIOSE  IDEAS", "GUILT", "HEADACHE", "HEADACHE", "heaviness in head/", "IMPULSIVE  BEH", "INC  IRRITABLE", "IRRITABLE/", "lack of confidence/", "LAUGHING  TO  SELF", "LOSS OF  CONC", "loss of enthusiasm/", "MUTTERING", "NEGLETS  CHILD", "NO  WORK", "NO WORK DUE TO FEAR", "not working/", "PR ON CHEST", "PR ON HEAD", "PR ON THROAT", "PREOCC SYMP", "pressured speech/", "PRICKING  PAIN  INTHROAT", "restlessness/", "RUMINATION", "self referenceciality/", "SEMEN  IN URINE", "SINGING  SONGS", "SMILING", "social withdrawal", "social withdrawal/", "social withdrawal/", "START  AS  CATATONIA", "STARTLE", "susidol ideas", "SUSPECTS  INFIDELITY", "t.n.head/", "t.n.limbs", "t.n.limbs/", "t.n.whole body/", "TALKATIVENESS", "URGENCY  TO MEET DOC", "WEEPING", "weeping spells", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList5.setName("jList5"); // NOI18N
        jScrollPane5.setViewportView(jList5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(20, 340, 180, 190);

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextArea1.setForeground(new java.awt.Color(0, 0, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane6.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(20, 270, 180, 76);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Scezoid"); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 207, -1, -1));

        jComboBox19.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox19.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox19.setName("p1"); // NOI18N
        jPanel5.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 232, 70, -1));

        jLabel20.setText("Paranoid"); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 207, -1, -1));

        jComboBox20.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox20.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox20.setName("P2"); // NOI18N
        jPanel5.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 227, 62, -1));

        jLabel21.setText("Hisrionic"); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 207, -1, -1));

        jComboBox21.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox21.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox21.setName("p3"); // NOI18N
        jPanel5.add(jComboBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 227, 83, -1));

        jLabel22.setText("Obsessive"); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 274, -1, -1));

        jComboBox22.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox22.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox22.setName("p4"); // NOI18N
        jPanel5.add(jComboBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 294, 83, -1));

        jLabel23.setText("Scizotypal"); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 274, -1, -1));

        jComboBox23.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox23.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox23.setName("p5"); // NOI18N
        jPanel5.add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 294, -1, -1));

        jLabel24.setText("Borderline"); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 274, -1, -1));

        jComboBox24.setFont(resourceMap.getFont("p4.font")); // NOI18N
        jComboBox24.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox24.setName("p6"); // NOI18N
        jPanel5.add(jComboBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 294, 80, -1));

        getContentPane().add(jPanel5);
        jPanel5.setBounds(750, 90, 380, 460);

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(80, 14, 180, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    Dignosis dg;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox21;
    private javax.swing.JComboBox jComboBox22;
    private javax.swing.JComboBox jComboBox23;
    private javax.swing.JComboBox jComboBox24;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JTextArea jComboBox8;
    private javax.swing.JTextArea jComboBox9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTextField2;
    private javax.swing.JTextArea jTextField3;
    // End of variables declaration//GEN-END:variables

    public void focusGained(FocusEvent e) {
        
        if(e.getSource()==jTextField2)
        jList1.setVisible(true);
        else
            jList2.setVisible(true);
       // throw new UnsupportedOperationException("Not supported yet.");
        
    }

    public void focusLost(FocusEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void valueChanged(ListSelectionEvent e) {
        Object[]fm,mh,othr,hallu,delu;
        StringBuffer s1=new StringBuffer();
         StringBuffer s2=new StringBuffer();
         StringBuffer s3=new StringBuffer();
          StringBuffer s4=new StringBuffer();
           StringBuffer s5=new StringBuffer();
        fm=null;
        mh=null;
        othr=null;
        hallu=null;
        delu=null;
      if(  e.getSource()==jList1){
      {
        fm=   jList1.getSelectedValues();
        if(fm!=null){
        for(int i=0;i<fm.length;i++)
            
                   s1.append(fm[i]);
                    s1.append(";");
                //  System.out.println(s1);
            }
      }
      
       jTextField2.setText(s1.toString()); 
    }
       if(  e.getSource()==jList2){
      {
        mh=   jList2.getSelectedValues();
        if(mh!=null){
        for(int i=0;i<mh.length;i++)
            
                   s2.append(mh[i]);
                    s2.append(";");
                //  System.out.println(s1);
            }
      }
      
       jTextField3.setText(s2.toString()); 
    }
     if(  e.getSource()==jList5){
      {
        othr=   jList5.getSelectedValues();
        if(othr!=null){
        for(int i=0;i<othr.length;i++)
            
                   s3.append(othr[i]);
                    s3.append(";");
                //  System.out.println(s1);
            }
      }
      
       jTextArea1.setText(s3.toString()); 
    }    
      if(  e.getSource()==jList3){
      {
        othr=   jList3.getSelectedValues();
        if(othr!=null){
        for(int i=0;i<othr.length;i++)
            
                   s4.append(othr[i]);
                    s4.append(";");
                //  System.out.println(s1);
            }
      }
      
       jComboBox8.setText(s4.toString()); 
    }    
      
      if(  e.getSource()==jList4){
      {
        othr=   jList4.getSelectedValues();
        if(othr!=null){
        for(int i=0;i<othr.length;i++)
            
                   s5.append(othr[i]);
                    s5.append(";");
                //  System.out.println(s1);
            }
      }
      
       jComboBox9.setText(s5.toString()); 
    }    
      
      // throw new UnsupportedOperationException("Not supported yet.");
    }
}
