/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dignosis.java
 *
 * Created on 29 Sep, 2011, 11:25:37 PM
 */
package netbeanjavaclinic;

import billingdesktopapplication.MyJPane;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.JTextComponent;

/**
 *
 * @author DELL
 */
public class Dignosis extends javax.swing.JFrame implements ActionListener,ListSelectionListener {
public PatientVO cvo;
Appointment apt;
    /** Creates new form Dignosis */
    public Dignosis() {
        initComponents();
        jComboBox1.setVisible(false);
         jComboBox2.setVisible(false);
          jComboBox3.setVisible(false);
           jComboBox4.setVisible(false);
       
        jList2.addListSelectionListener(this);
        jButton1.addActionListener(this);
        // jButton2.addActionListener(this);
       //jList2.setVisible(false);
         this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jDialog1.setName("jDialog1"); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(netbeanjavaclinic.NetbeanJavaClinicApp.class).getContext().getResourceMap(Dignosis.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 140, 30));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setName("jComboBox2"); // NOI18N
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 128, 28));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 73, 25));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 121, 28));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setName("jComboBox4"); // NOI18N
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 124, 30));

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 240, 40));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList2.setFont(resourceMap.getFont("jList2.font")); // NOI18N
        jList2.setForeground(resourceMap.getColor("jList2.foreground")); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "ADHD", "Alcho.Dep", "Alcho.Hallu", "Anorexia Nervosa", "B.M.D.", "B.P.D.", "B.R.P.", "Bipolar-depre", "Bipolar-mania", "Bipolar-mixed", "BipolarII", "Bullimai Nervosa", "Catatonia", "Delu.Dis", "Dementia", "Dementia wirth Behv Dist", "G.A.D.", "Grief Reaction", "Grief Complicated", "Grief Delayed", "Hypochondriasis", "Hys.Conversion", "Hys.dissociation", "Hys.Dysphoria", "Hys.Psychosis", "M.D.D.", "M.D.D. with Psychotic f", "Migraine", "M.R.", "M.R.with Bhaviourial Distrb", "Monodel.Hypo.", "O.C.D.", "P.T.S.D.", "Panic.DIs", "Phobia Specific", "PSY.Pain Dis", "Psy.Sexual Dis", "Psy.Somatic DIs", "S.A.D.", "Schiz.Form.Dis", "Schiz Paranoid", "Schiz Simple", "Schiz chronic", "Seizure dis-generalized", "Seizure-Partial complex", "Somatoform dis", " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setName("jList2"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextArea1.setForeground(resourceMap.getColor("jTextArea1.foreground")); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 230));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextArea2.setForeground(resourceMap.getColor("jTextArea2.foreground")); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setName("jTextArea2"); // NOI18N
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 380, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Dignosis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
     public void setText(String s)
     {
        // jTextField1.setText(s);
     }
   
    public void actionPerformed(ActionEvent e) {
  /*      
      if(e.getSource()==jButton2)
      {
         System.out.println("calendar");
     MyJPane mjp=new MyJPane(new JPanel(),this);
            
            Container cp=this.getContentPane() ;
		cp.add(mjp);
              this.resize(1000,1000);
      }
        
      else
      {
            try {
                String s=jTextField1.getText();
                String d[]=s.split("-");
              //  String d1[]={d[2],d[0],d[1]};
                String s1=d[2]+"-"+d[0]+"-"+d[1];
             // Date fd=new Date(Integer.parseInt(d[0]),Integer.parseInt(d[1]),Integer.parseInt(d[2]));
              // System.out.println("ap called");
               
               
               SimpleDateFormat d1=new SimpleDateFormat("yyyy-dd-mm");
                //  SimpleDateFormat d1=new SimpleDateFormat("dd-mm-yyyy");
                 d1.setLenient(false);
                 
           JFormattedTextField jtff=    new JFormattedTextField(d1);
            //  String s=jTextField1.getText();
              System.out.println("dt"+s1);
              try{
                    d1.parse(s1);
                    
              }
              catch(ParseException pe){
                  
                  
                  System.out.println("in catch");
               JOptionPane.showMessageDialog(jTextField1,"no dt format","Error Dialog",
                     JOptionPane.ERROR_MESSAGE);
              // jTextField1.setText("");
                /*   System.out.println("in catch");
              InputVerifier verifier = new InputVerifier() {
             public boolean verify(JComponent input) {
               final JTextComponent source = (JTextComponent) input;
               JOptionPane.showMessageDialog(source, "Can't leave.", "Error Dialog",
                     JOptionPane.ERROR_MESSAGE);
              /* String text = source.getText();
               if ((text.length() != 0) && !(text.equals("Exit"))) {
                 JOptionPane.showMessageDialog(source, "Can't leave.", "Error Dialog",
                     JOptionPane.ERROR_MESSAGE);
                 return false;
               } else {
                 return false;
               }
             
           };
               jTextField1.setInputVerifier(verifier);
              }
          
              }
     */
               //this.cvo.digno=(String)jComboBox1.getSelectedItem();
                this.cvo.digno=(String)jTextArea1.getText(); 
               //this.cvo.m1=(String)jComboBox2.getSelectedItem(); 
                this.cvo.m1=(String)jTextArea2.getText(); 
              // this.cvo.m2=(String)jComboBox3.getSelectedItem(); 
              // this.cvo.m3=(String)jComboBox4.getSelectedItem(); 
               
            //  String d[]=s.split("-");
            //  Date fd=new Date(Integer.parseInt(d[0]),Integer.parseInt(d[1]),Integer.parseInt(d[2]));
                   //this.cvo.followdt=Date.valueOf(s1) ;
             
            //this.cvo.followdt= fd ;
              
             /* java.sql.Date ud=Date.valueOf(s1);
              System.out.println("ud"+ud);
            Vector vo= (Vector) PatientDao.selectPatient(ud);
            Iterator it=vo.iterator();
            while(it.hasNext())
            {
                System.out.println(it.next());
            }
            jList1.setListData(vo);
            System.out.println("vc"+vo);
              this.cvo.followdt=new java.sql.Date(ud.getTime());
              System.out.println("dt1"+cvo.followdt);
              
              System.out.println("yes...");
            //  this.cvo.followdt=ud;
             int x=  PatientDao.insertCust(cvo);
               System.out.println(cvo);
                  if(x==1)
                  {
                      
                JOptionPane.showMessageDialog(this,"Record Saved");
              int option= JOptionPane.showConfirmDialog(this, "Do you want to continue?","",JOptionPane.YES_NO_OPTION);
                
                if(option==JOptionPane.YES_OPTION)
                {
                   //  NetbeanJavaClinicApp.getInstance().nbjc;
               System.out.println(option);
               System.exit(0); 
                  //  NetbeanJavaClinicApp.main(args);
              
                  }
                  else
                  {  
                JOptionPane.showMessageDialog(this,"Record Could not be Saved");
               System.exit(0);
               
                  }
              //System.exit(0);*/
             /*String s= jTextField1.getText();
            String[] split = s.split("-");
               int d=Integer.parseInt(split[0]);
            int m=Integer.parseInt(split[1]);
                int y=Integer.parseInt(split[2]);
                java.util.Date ud=new java.util.Date(d,m,y);*/
            //  java.sql.Date ud=Date.valueOf(s);
                 //   this.cvo.followdt=new java.sql.Date(ud.getTime());*/
             //  Date dt=new Date(1,1,2001);
               this.cvo.followdt=new Date(1,1,2001);
               PatientDao.insertCust(cvo);
               System.out.println(cvo);
               
               apt=new Appointment(cvo.reg,cvo);
               apt.setVisible (true);
               this.setVisible(false); 
            //  jDialog1.show();
              // System.exit(0);
              //System.exit(0);
                 
            } //catch (SQLException ex) {
              //  Logger.getLogger(Dignosis.class.getName()).log(Level.SEVERE, null, ex);
          //  }

    public void valueChanged(ListSelectionEvent e) {
         Object[]fm;
        StringBuffer s1=new StringBuffer();
        
        fm=null;
        
     
        fm=   jList2.getSelectedValues();
        if(fm!=null){
        for(int i=0;i<fm.length;i++)
        {
                   s1.append(fm[i]);
                    s1.append(";");
                    s1.append("\n") ;
                //  System.out.println(s1);
        }
      
       jTextArea1.setText(s1.toString()); 
    }
    }
   
    
    
}
