/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prescription1.java
 *
 * Created on 7 Dec, 2011, 8:54:55 PM
 */
package netbeanjavaclinic;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import java.text.SimpleDateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author DELL
 */
public class Prescription2 extends javax.swing.JPanel implements ActionListener {

    /** Creates new form Prescription1 */
    PatientVO pvo;
    HashMap hm;
    JFrame j1;
    static int c;
    // Vector v;

    public Prescription2(PatientVO vo) {
        initComponents();
        
      // ImageIcon im=new ImageIcon("f:\\img1.jpeg");
       // jLabel1.setIcon(im);
       
        c++;
        pvo = vo;
        System.out.print("pr"+c);
        //jLabel2.setText("" + pvo.reg);
        //jLabel3.setText(pvo.name);
         jLabel5.setText("" + pvo.reg);
        jLabel6.setText(pvo.name);
        
        // ImageIcon imc=new ImageIcon("f:/img2.jpg");
 //   ImageIcon imc=new ImageIcon("/img2.jpg");
        //ImageIcon imc=new ImageIcon("/img3.bmp");
       // jLabel1.setIcon(imc);
        
        hm = new HashMap();
        hm.put("1", "nil");
        hm.put("2", "nil");
        hm.put("3", "nil");
        hm.put("4", "nil");
        hm.put("5", "nil");
        hm.put("6", "nil");
        hm.put("7", "nil");

        //  j1=j;

        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel18.setVisible(false);
        jLabel20.setVisible(false);
        jLabel22.setVisible(false);
        jLabel26.setVisible(false);
        
  


        // v=new Vector();

        //PatientVO vo
        // pvo=vo;
        jButton1.addActionListener(this);
        jComboBox4.addActionListener(this);
        jComboBox5.addActionListener(this);
        jComboBox7.addActionListener(this);
        jComboBox35.addActionListener(this);
        jComboBox8.addActionListener(this);
        jComboBox29.addActionListener(this);
        jComboBox3.addActionListener(this);







        //  jLabel2.setText(""+pvo.reg);
        // jLabel3.setText(pvo.name);
      //  SimpleDateFormat dateFormat = new SimpleDateFormat("dd/mm/yy"); 
  java.util.Date date = new java.util.Date(); 
//  System.out.println("Current Date : " + dateFormat.format(date)); 
        java.sql.Date sd=new  java.sql.Date(date.getTime());
         jLabel7.setText(""+sd);
        //String d=new java.util.Date().
       // jLabel7.setText(dateFormat.format(date));
      //  jLabel4.setText(new java.util.Date().toString());
        this.setSize(500, 500);
        //  jComboBox8.setVisible(false);
    }

    public static void main(String[] args) {
        /*  
        JFrame j=new JFrame();
        
        Prescription2 p1=new Prescription2(j);
        j.add(p1);
        j.setSize(600,600);
        j.setVisible(true);
        System.out.println("hi..");
         */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox29 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox35 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 57, 364, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setName("jLabel4"); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 57, -1, -1));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setName("jSeparator3"); // NOI18N
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 789, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 57, 364, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel23.setForeground(new java.awt.Color(0, 0, 153));
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 60, 22));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("D/A"); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 75, 22));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setForeground(new java.awt.Color(0, 0, 153));
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 60, 22));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setForeground(new java.awt.Color(0, 0, 153));
        jLabel27.setName("jLabel27"); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 60, 22));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 60, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jComboBox4.setEditable(true);
        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox4.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setName("jComboBox4"); // NOI18N
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 28));

        jButton1.setName("jButton1"); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 350, -1));

        jComboBox29.setEditable(true);
        jComboBox29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox29.setName("jComboBox29"); // NOI18N
        jPanel2.add(jComboBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 28));

        jComboBox5.setEditable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(netbeanjavaclinic.NetbeanJavaClinicApp.class).getContext().getResourceMap(Prescription2.class);
        jComboBox5.setFont(resourceMap.getFont("jComboBox5.font")); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setName("jComboBox5"); // NOI18N
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, 28));

        jComboBox8.setEditable(true);
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.setName("jComboBox8"); // NOI18N
        jPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 120, 28));

        jComboBox35.setEditable(true);
        jComboBox35.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox35.setName("jComboBox35"); // NOI18N
        jPanel2.add(jComboBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 120, 28));

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 28));

        jComboBox7.setEditable(true);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setName("jComboBox7"); // NOI18N
        jPanel2.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 28));

        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField1.setForeground(new java.awt.Color(51, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 50, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField2.setForeground(new java.awt.Color(51, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.setNextFocusableComponent(jTextField3);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 50, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField3.setForeground(new java.awt.Color(51, 0, 0));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 50, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField4.setForeground(new java.awt.Color(51, 0, 0));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        jTextField4.setName("jTextField4"); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField5.setForeground(new java.awt.Color(51, 0, 0));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(null);
        jTextField5.setName("jTextField5"); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 50, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField6.setForeground(new java.awt.Color(51, 0, 0));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(null);
        jTextField6.setName("jTextField6"); // NOI18N
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 50, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField7.setForeground(new java.awt.Color(51, 0, 0));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(null);
        jTextField7.setName("jTextField7"); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 50, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField8.setForeground(new java.awt.Color(51, 0, 0));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(null);
        jTextField8.setName("jTextField8"); // NOI18N
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 50, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField9.setForeground(new java.awt.Color(51, 0, 0));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jTextField9.setName("jTextField9"); // NOI18N
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 50, 30));

        jTextField10.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField10.setForeground(new java.awt.Color(51, 0, 0));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(null);
        jTextField10.setName("jTextField10"); // NOI18N
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 50, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField11.setForeground(new java.awt.Color(51, 0, 0));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(null);
        jTextField11.setName("jTextField11"); // NOI18N
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 50, 30));

        jTextField12.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField12.setForeground(new java.awt.Color(51, 0, 0));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(null);
        jTextField12.setName("jTextField12"); // NOI18N
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 50, 30));

        jTextField13.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField13.setForeground(new java.awt.Color(51, 0, 0));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(null);
        jTextField13.setName("jTextField13"); // NOI18N
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 50, 30));

        jTextField14.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField14.setForeground(new java.awt.Color(51, 0, 0));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(null);
        jTextField14.setName("jTextField14"); // NOI18N
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 50, 30));

        jTextField15.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField15.setForeground(new java.awt.Color(51, 0, 0));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setBorder(null);
        jTextField15.setName("jTextField15"); // NOI18N
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 50, 30));

        jTextField16.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField16.setForeground(new java.awt.Color(51, 0, 0));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setBorder(null);
        jTextField16.setName("jTextField16"); // NOI18N
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 50, 30));

        jTextField17.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField17.setForeground(new java.awt.Color(51, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setBorder(null);
        jTextField17.setName("jTextField17"); // NOI18N
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 50, 30));

        jTextField18.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField18.setForeground(new java.awt.Color(51, 0, 0));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setBorder(null);
        jTextField18.setName("jTextField18"); // NOI18N
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 50, 30));

        jTextField19.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField19.setForeground(new java.awt.Color(51, 0, 0));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setBorder(null);
        jTextField19.setName("jTextField19"); // NOI18N
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 50, 30));

        jTextField20.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField20.setForeground(new java.awt.Color(51, 0, 0));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setBorder(null);
        jTextField20.setName("jTextField20"); // NOI18N
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 50, 30));

        jTextField21.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField21.setForeground(new java.awt.Color(51, 0, 0));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setBorder(null);
        jTextField21.setName("jTextField21"); // NOI18N
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 50, 30));

        jTextField22.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField22.setForeground(new java.awt.Color(51, 0, 0));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setBorder(null);
        jTextField22.setName("jTextField22"); // NOI18N
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 50, 30));

        jTextField23.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField23.setForeground(new java.awt.Color(51, 0, 0));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setBorder(null);
        jTextField23.setName("jTextField23"); // NOI18N
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 50, 30));

        jTextField24.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField24.setForeground(new java.awt.Color(51, 0, 0));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setBorder(null);
        jTextField24.setName("jTextField24"); // NOI18N
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 50, 30));

        jTextField25.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField25.setForeground(new java.awt.Color(51, 0, 0));
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setBorder(null);
        jTextField25.setName("jTextField25"); // NOI18N
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 50, 30));

        jTextField26.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField26.setForeground(new java.awt.Color(51, 0, 0));
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setBorder(null);
        jTextField26.setName("jTextField26"); // NOI18N
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 50, 30));

        jTextField27.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField27.setForeground(new java.awt.Color(51, 0, 0));
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setBorder(null);
        jTextField27.setName("jTextField27"); // NOI18N
        jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 50, 30));

        jTextField28.setFont(new java.awt.Font("Tahoma", 3, 12));
        jTextField28.setForeground(new java.awt.Color(51, 0, 0));
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setBorder(null);
        jTextField28.setName("jTextField28"); // NOI18N
        jPanel2.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 50, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 130, 20));

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        jLabel22.setForeground(new java.awt.Color(0, 0, 153));
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        jLabel26.setForeground(new java.awt.Color(0, 0, 153));
        jLabel26.setName("jLabel26"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 280));

        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 330, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 940, 820));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox29;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox35;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {

        System.out.println("called");
        if (e.getSource() == jComboBox7) {
            System.out.println("called1");
            hm.put("1", jComboBox7.getSelectedItem().toString());
            jLabel14.setVisible(true);
             jLabel14.setText(jComboBox7.getSelectedItem().toString());
             
        }
        if (e.getSource() == jComboBox29) {
            //System.out.println("called1");
            hm.put("2", jComboBox29.getSelectedItem().toString());
             jLabel15.setVisible(true);
            jLabel15.setText(jComboBox29.getSelectedItem().toString()); 
           
        }
        if (e.getSource() == jComboBox5) {
            //System.out.println("called1");
            hm.put("3", jComboBox5.getSelectedItem().toString());
            jLabel16.setVisible(true);
              jLabel16.setText(jComboBox5.getSelectedItem().toString());
              
        }
        if (e.getSource() == jComboBox8) {
            //System.out.println("called1");
            hm.put("4", jComboBox8.getSelectedItem().toString());
            jLabel18.setVisible(true);
             jLabel18.setText(jComboBox8.getSelectedItem().toString());
        }
        if (e.getSource() == jComboBox35) {
            //System.out.println("called1");
            hm.put("5", jComboBox35.getSelectedItem().toString());
            jLabel20.setVisible(true);
             jLabel20.setText(jComboBox35.getSelectedItem().toString());
        }
        if (e.getSource() == jComboBox3) {
            //System.out.println("called1");
            hm.put("6", jComboBox3.getSelectedItem().toString());
            jLabel22.setVisible(true);
             jLabel22.setText(jComboBox3.getSelectedItem().toString());
        }
        if (e.getSource() == jComboBox4) {
            //System.out.println("called1");
            hm.put("7", jComboBox4.getSelectedItem().toString());
            jLabel26.setVisible(true);
             jLabel26.setText(jComboBox4.getSelectedItem().toString());
            
            

            //  jLabel6.setText(  jComboBox4.getSelectedItem().toString());

            //         }

            //  jComboBox4.setVisible(false);
            //throw new UnsupportedOperationException("Not supported yet.");
        }


      System.out.println(hm);



        //  jLabel6.setText(  jComboBox4.getSelectedItem().toString());

        //         }
        //<editor-fold defaultstate="collapsed" desc="comment">
        if //</editor-fold>
                (e.getSource() == jButton1) {
            //Container c=getContentPane();
            //   j1.add(jLayeredPane1);
            //  jLayeredPane1.setVisible(true);
            //   
            //   jLabel12.setText(hm.get("1").toString());
            //   
           /* jLabel1.setText(jComboBox7.getSelectedItem().toString());
             jLabel5.setText(jComboBox29.getSelectedItem().toString()); 
             jLabel6.setText(jComboBox5.getSelectedItem().toString());
             jLabel10.setText(jComboBox8.getSelectedItem().toString());
              jLabel9.setText(jComboBox35.getSelectedItem().toString());
               jLabel11.setText(jComboBox3.getSelectedItem().toString());
                jLabel12.setText(jComboBox4.getSelectedItem().toString());
            
            */
            
            
            
            
            System.out.println("hm" + hm);
            jComboBox4.setVisible(false);
            jComboBox5.setVisible(false);
            jComboBox7.setVisible(false);
            jComboBox35.setVisible(false);
            jComboBox8.setVisible(false);
            jComboBox29.setVisible(false);
            jComboBox3.setVisible(false);

            /*jLabel1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel10.setVisible(true);
            jLabel9.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);*/

         /*       
            jLabel1.setText(hm.get("1").toString());
            jLabel5.setText(hm.get("2").toString());
          //  if(hm.get("2").toString().equals("nil"))
           //     jLabel5.setVisible(false);
            jLabel6.setText(hm.get("3").toString());
           // if(hm.get("3").toString().equals("nil"))
           //     jLabel6.setVisible(false);
            jLabel10.setText(hm.get("4").toString());
          //  if(hm.get("4").toString().equals("nil"))
          //      jLabel10.setVisible(false);
            jLabel9.setText(hm.get("5").toString());
          //   if(hm.get("5").toString().equals("nil"))
          //      jLabel9.setVisible(false);
              jLabel11.setText(hm.get("6").toString());
         //     if(hm.get("6").toString().equals("nil"))
         //       jLabel1.setVisible(false);
            jLabel12.setText(hm.get("7").toString());
          //     if(hm.get("7").toString().equals("nil"))
          //      jLabel12.setVisible(false);
          * 
          */
               
         if(jLabel14.getText().equals("jLabel14"))
                jLabel14.setVisible(false);
            if(jLabel15.getText().equals("jLabel15"))
                jLabel15.setVisible(false);
            if(jLabel16.getText().equals("jLabel16"))
                jLabel16.setVisible(false);
            if(jLabel18.getText().equals("jLabel18"))
                jLabel18.setVisible(false);
            if(jLabel20.getText().equals("jLabel20"))
                jLabel20.setVisible(false);
            if(jLabel22.getText().equals("jLabel22"))
                jLabel22.setVisible(false);
            if(jLabel26.getText().equals("jLabel26"))
                jLabel26.setVisible(false); 
         
            
            this.jPanel2.setBackground(Color.white);
             this.jPanel3.setBackground(Color.white);
            this.setBackground(Color.white);
            
            // jLabel1.setText(hm.get("1").toString());
                  jSeparator3.setVisible(false);
              jButton1.setVisible(false);

        }

        //  jComboBox4.setVisible(false);
        //throw new UnsupportedOperationException("Not supported yet.");

    }
}
