/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prescription1.java
 *
 * Created on 7 Dec, 2011, 8:54:55 PM
 */
package dumps;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import netbeanjavaclinic.PatientVO;

/**
 *
 * @author DELL
 */
public class Prescription1 extends javax.swing.JPanel implements ActionListener {
    /** Creates new form Prescription1 */
    PatientVO pvo;
    HashMap hm;
    JFrame j1;
   // Vector v;
    
    public Prescription1(JFrame j) {
        initComponents();
         hm=new HashMap();
        j1=j;
        
     //   ImageIcon imc=new ImageIcon("f:/img2.jpg");
       // jLabel14.setIcon(imc);
     //  JLabel imgL = new JLabel("Image", imc, JLabel.CENTER);
       
      // jLabel23.setIcon(new ImageIcon("/i1.png"));
     //  jPanel4.setLayout(new BorderLayout());
     //  jPanel4.add(imgL);
      //    jInternalFrame1.add(imgL);
        jLabel1.setVisible(false);
         jLabel5.setVisible(false);
          jLabel6.setVisible(false);
           jLabel10.setVisible(false);
            jLabel9.setVisible(false);
             jLabel11.setVisible(false);
            jLabel12.setVisible(false);  
        
        
        
       
       // v=new Vector();
        
        //PatientVO vo
        // pvo=vo;
        jButton1.addActionListener(this);
         jComboBox4.addActionListener(this);
         jComboBox5.addActionListener(this);
         jComboBox7.addActionListener(this);
         jComboBox35.addActionListener(this);
         jComboBox8.addActionListener(this);
         jComboBox29.addActionListener(this);
         jComboBox3.addActionListener(this);
         
         
         
         
         
         
         
       //  jLabel2.setText(""+pvo.reg);
        // jLabel3.setText(pvo.name);
         jLabel4.setText(new java.util.Date().toString());
         jComboBox8.setVisible(false);
    }
    public static void main(String[] args)
    {
        
        JFrame j=new JFrame();
       
        Prescription1 p1=new Prescription1(j);
         j.add(p1);
         j.setSize(600,600);
        j.setVisible(true);
        System.out.println("hi..");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox29 = new javax.swing.JComboBox();
        jComboBox30 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox35 = new javax.swing.JComboBox();
        jComboBox37 = new javax.swing.JComboBox();
        jComboBox38 = new javax.swing.JComboBox();
        jComboBox39 = new javax.swing.JComboBox();
        jComboBox40 = new javax.swing.JComboBox();
        jComboBox41 = new javax.swing.JComboBox();
        jComboBox42 = new javax.swing.JComboBox();
        jComboBox43 = new javax.swing.JComboBox();
        jComboBox44 = new javax.swing.JComboBox();
        jComboBox45 = new javax.swing.JComboBox();
        jComboBox46 = new javax.swing.JComboBox();
        jComboBox47 = new javax.swing.JComboBox();
        jComboBox48 = new javax.swing.JComboBox();
        jComboBox25 = new javax.swing.JComboBox();
        jComboBox26 = new javax.swing.JComboBox();
        jComboBox27 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox49 = new javax.swing.JComboBox();
        jComboBox50 = new javax.swing.JComboBox();
        jComboBox51 = new javax.swing.JComboBox();
        jComboBox52 = new javax.swing.JComboBox();
        jComboBox53 = new javax.swing.JComboBox();
        jComboBox54 = new javax.swing.JComboBox();
        jComboBox55 = new javax.swing.JComboBox();
        jComboBox56 = new javax.swing.JComboBox();
        jComboBox57 = new javax.swing.JComboBox();
        jComboBox58 = new javax.swing.JComboBox();
        jComboBox59 = new javax.swing.JComboBox();
        jComboBox60 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox24 = new javax.swing.JComboBox();
        jComboBox66 = new javax.swing.JComboBox();
        jComboBox68 = new javax.swing.JComboBox();
        jComboBox69 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox62 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel14 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(netbeanjavaclinic.NetbeanJavaClinicApp.class).getContext().getResourceMap(Prescription1.class);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 57, 364, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setName("jLabel4"); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 57, -1, -1));

        jPanel2.setName("jPanel2"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jComboBox29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox29.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox29.setName("jComboBox29"); // NOI18N

        jComboBox30.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox30.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox30.setName("jComboBox30"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setIcon(resourceMap.getIcon("jLabel23.icon")); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("netbeanjavaclinic/resources/MyResources"); // NOI18N
        jLabel23.setText(bundle.getString("n1")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setIcon(resourceMap.getIcon("jLabel24.icon")); // NOI18N
        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbeanjavaclinic/resources/४४.png"))); // NOI18N
        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbeanjavaclinic/resources/५५.png"))); // NOI18N
        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        jComboBox35.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox35.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox35.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox35.setName("jComboBox35"); // NOI18N

        jComboBox37.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox37.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox37.setName("jComboBox37"); // NOI18N

        jComboBox38.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox38.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox38.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox38.setName("jComboBox38"); // NOI18N

        jComboBox39.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox39.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox39.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox39.setName("jComboBox39"); // NOI18N

        jComboBox40.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox40.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox40.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox40.setName("jComboBox40"); // NOI18N

        jComboBox41.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox41.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox41.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox41.setName("jComboBox41"); // NOI18N

        jComboBox42.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox42.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox42.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox42.setName("jComboBox42"); // NOI18N

        jComboBox43.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox43.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox43.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox43.setName("jComboBox43"); // NOI18N

        jComboBox44.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox44.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox44.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox44.setName("jComboBox44"); // NOI18N

        jComboBox45.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox45.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox45.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox45.setName("jComboBox45"); // NOI18N

        jComboBox46.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox46.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox46.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox46.setName("jComboBox46"); // NOI18N

        jComboBox47.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox47.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox47.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox47.setName("jComboBox47"); // NOI18N

        jComboBox48.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox48.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox48.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox48.setName("jComboBox48"); // NOI18N

        jComboBox25.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox25.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox25.setName("jComboBox25"); // NOI18N

        jComboBox26.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox26.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox26.setName("jComboBox26"); // NOI18N

        jComboBox27.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox27.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox27.setName("jComboBox27"); // NOI18N

        jComboBox10.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox10.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox10.setName("jComboBox10"); // NOI18N

        jComboBox49.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox49.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox49.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox49.setName("jComboBox49"); // NOI18N

        jComboBox50.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox50.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox50.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox50.setName("jComboBox50"); // NOI18N

        jComboBox51.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox51.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox51.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox51.setName("jComboBox51"); // NOI18N

        jComboBox52.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox52.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox52.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox52.setName("jComboBox52"); // NOI18N

        jComboBox53.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox53.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox53.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox53.setName("jComboBox53"); // NOI18N

        jComboBox54.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox54.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox54.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox54.setName("jComboBox54"); // NOI18N

        jComboBox55.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox55.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox55.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox55.setName("jComboBox55"); // NOI18N

        jComboBox56.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox56.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox56.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox56.setName("jComboBox56"); // NOI18N

        jComboBox57.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox57.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox57.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox57.setName("jComboBox57"); // NOI18N

        jComboBox58.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox58.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox58.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox58.setName("jComboBox58"); // NOI18N

        jComboBox59.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox59.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox59.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox59.setName("jComboBox59"); // NOI18N

        jComboBox60.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox60.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox60.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", ".5", "1", "2", "3" }));
        jComboBox60.setName("jComboBox60"); // NOI18N

        jComboBox12.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox12.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox12.setName("jComboBox12"); // NOI18N

        jComboBox24.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox24.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox24.setName("jComboBox24"); // NOI18N

        jComboBox66.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox66.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox66.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox66.setName("jComboBox66"); // NOI18N

        jComboBox68.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox68.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox68.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox68.setName("jComboBox68"); // NOI18N

        jComboBox69.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox69.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox69.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox69.setName("jComboBox69"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbeanjavaclinic/resources/२२.png"))); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setName("jLabel13"); // NOI18N

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox4.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setName("jComboBox4"); // NOI18N

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox5.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setName("jComboBox5"); // NOI18N

        jComboBox62.setFont(new java.awt.Font("Tahoma", 3, 12));
        jComboBox62.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox62.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Alternate" }));
        jComboBox62.setName("jComboBox62"); // NOI18N

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox7.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setName("jComboBox7"); // NOI18N

        jComboBox8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox8.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.setName("jComboBox8"); // NOI18N

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox3.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setName("jLabel8"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setName("jPanel4"); // NOI18N

        jInternalFrame1.setBackground(resourceMap.getColor("jInternalFrame1.background")); // NOI18N
        jInternalFrame1.setBorder(null);
        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox59, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jComboBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox62, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox68, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox69, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox12, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox40, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox24, 0, 80, Short.MAX_VALUE)
                            .addComponent(jComboBox66, 0, 80, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(460, 460, 460)
                                        .addComponent(jLabel13)))))
                        .addGap(329, 329, 329))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(277, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel13))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jComboBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(300, 300, 300)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jComboBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox50, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox56, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox54, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox57, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox58, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox59, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jComboBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox52, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox53, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox60, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jComboBox62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jComboBox69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 490));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox24;
    private javax.swing.JComboBox jComboBox25;
    private javax.swing.JComboBox jComboBox26;
    private javax.swing.JComboBox jComboBox27;
    private javax.swing.JComboBox jComboBox29;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox30;
    private javax.swing.JComboBox jComboBox35;
    private javax.swing.JComboBox jComboBox37;
    private javax.swing.JComboBox jComboBox38;
    private javax.swing.JComboBox jComboBox39;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox40;
    private javax.swing.JComboBox jComboBox41;
    private javax.swing.JComboBox jComboBox42;
    private javax.swing.JComboBox jComboBox43;
    private javax.swing.JComboBox jComboBox44;
    private javax.swing.JComboBox jComboBox45;
    private javax.swing.JComboBox jComboBox46;
    private javax.swing.JComboBox jComboBox47;
    private javax.swing.JComboBox jComboBox48;
    private javax.swing.JComboBox jComboBox49;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox50;
    private javax.swing.JComboBox jComboBox51;
    private javax.swing.JComboBox jComboBox52;
    private javax.swing.JComboBox jComboBox53;
    private javax.swing.JComboBox jComboBox54;
    private javax.swing.JComboBox jComboBox55;
    private javax.swing.JComboBox jComboBox56;
    private javax.swing.JComboBox jComboBox57;
    private javax.swing.JComboBox jComboBox58;
    private javax.swing.JComboBox jComboBox59;
    private javax.swing.JComboBox jComboBox60;
    private javax.swing.JComboBox jComboBox62;
    private javax.swing.JComboBox jComboBox66;
    private javax.swing.JComboBox jComboBox68;
    private javax.swing.JComboBox jComboBox69;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        
        System.out.println("called");
      /*  if(e.getSource()==jComboBox4)
        {
             //System.out.println("called1");
            hm.put("1",jComboBox4.getSelectedItem().toString());
             
      //  jLabel6.setText(  jComboBox4.getSelectedItem().toString());
         
       //         }
        
      //  jComboBox4.setVisible(false);
        //throw new UnsupportedOperationException("Not supported yet.");
        }*/
          if(e.getSource()==jComboBox5)
        {
             //System.out.println("called1");
            hm.put("2",jComboBox5.getSelectedItem().toString());
          } 
            if(e.getSource()==jComboBox7)
        {
             //System.out.println("called1");
            hm.put("3",jComboBox7.getSelectedItem().toString());
          }   
              if(e.getSource()==jComboBox35)
        {
             //System.out.println("called1");
            hm.put("4",jComboBox35.getSelectedItem().toString());
          }   
            /*    if(e.getSource()==jComboBox8)
        {
             //System.out.println("called1");
            hm.put("5",jComboBox8.getSelectedItem().toString());
          } */
                       if(e.getSource()==jComboBox29)
        {
             //System.out.println("called1");
            hm.put("6",jComboBox29.getSelectedItem().toString());
          }   
                if(e.getSource()==jComboBox3)
        {
             //System.out.println("called1");
            hm.put("7",jComboBox3.getSelectedItem().toString());
          }   
      //  jLabel6.setText(  jComboBox4.getSelectedItem().toString());
         
       //         }
                //<editor-fold defaultstate="collapsed" desc="comment">
                if
                        //</editor-fold>
(e.getSource()==jButton1)
                {
                    //Container c=getContentPane();
                 //   j1.add(jLayeredPane1);
                  //  jLayeredPane1.setVisible(true);
                 //   
                 //   jLabel12.setText(hm.get("1").toString());
                 //   
                    System.out.println("hm"+hm);
                    jComboBox4.setVisible(false);
                    jComboBox5.setVisible(false);
                   // jComboBox7.setVisible(false);
                    jComboBox35.setVisible(false);
                    jComboBox8.setVisible(false);
                    jComboBox29.setVisible(false);
                    jComboBox3.setVisible(false);
                   
                  jLabel1.setVisible(true);
         jLabel5.setVisible(true);
          jLabel6.setVisible(true);
           jLabel10.setVisible(true);
            jLabel9.setVisible(true);
             jLabel11.setVisible(true);
             jLabel12.setVisible(true);
               
                    
                    jLabel1.setText(hm.get("1").toString());
                     jLabel5.setText(hm.get("2").toString());
                    jLabel6.setText(hm.get("3").toString());
                     jLabel10.setText(hm.get("4").toString());
                    jLabel9.setText(hm.get("5").toString());
                    jLabel11.setText(hm.get("6").toString());
                     jLabel12.setText(hm.get("7").toString());
                   // jLabel1.setText(hm.get("1").toString());
                    
                    
                    
                }
        
      //  jComboBox4.setVisible(false);
        //throw new UnsupportedOperationException("Not supported yet.");
   
    }    
   
}
